### ISSUE TITLE
NSData Wiping Issues

### ISSUE THREAD

**Issue by ay-kay** [project-imas/memory-security#6]
Seems that _NSData_ wipe works quite well on your demo, in which the NSData object is initialized using NSData's _dataWithBytes:_. 

However, if NSData is created out of an NSString object using [dataUsingEncoding:](https://developer.apple.com/library/prerelease/iOS/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/index.html#//apple_ref/occ/instm/NSString/dataUsingEncoding:), depending on the string size, the actual data portion seems not to be placed straight after the header. Instead, it seems that at position _NSDATA_START_ADDRESS + 0x10_ a pointer points to the actual data space. In consequence, the current implementation would fail to properly wipe the actual data from memory. 

Are you able to reproduce that issue? 
Maybe NSData's [bytes](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSData_Class/Reference/Reference.html#//apple_ref/doc/uid/20000172-CIAEAJGI) method might be an option to determine the actual data location in memory (this would also resolve the difficulties of changing offsets for NSData)?

**Comment by gavin-black** [comment]
Hi @ay-kay,

Appreciate you taking the time to try iMAS and for finding that bug.  I was able to reproduce the issue easily thanks to your description.  I put in a quick update(cb67137) using bytes like you suggested for NSData.  It seems to be working, although there is some fun casting going on (Forcing it to ignore constant areas of memory :P).  Let me know if you run into any more issues.
